In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
data_test = pd.read_csv('mnist_test.csv')
data_train = pd.read_csv('mnist_train.csv')

In [3]:
data_test.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [4]:
data_train.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [5]:
data_train.shape

(60000, 785)

In [6]:
data_test.shape

(10000, 785)

In [7]:
X_train = data_train.iloc[:,1:786]
X_test = data_test.iloc[:,1:786]
y_train = data_train.iloc[:,0]
y_test = data_test.iloc[:,0]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_dev, y_train, y_dev = train_test_split(X_train, y_train, test_size = 0.2)

In [10]:
X_dev.shape

(12000, 784)

In [11]:
X_test.shape

(10000, 784)

In [12]:
X_train.shape

(48000, 784)

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
from sklearn.metrics import classification_report

In [15]:
#training random Forest to tune n_estimators
my_list = list(range(10,101,10))
for i in my_list:
    rf=RandomForestClassifier(n_estimators=i, random_state = 42)
    rf.fit(X_train,y_train)
    print (f"Accuracy Score for n_estimator = {i}")
    print(rf.score(X_train, y_train))

Accuracy Score for n_estimator = 10
0.999
Accuracy Score for n_estimator = 20
0.9998541666666667
Accuracy Score for n_estimator = 30
0.9999375
Accuracy Score for n_estimator = 40
0.9999791666666666
Accuracy Score for n_estimator = 50
1.0
Accuracy Score for n_estimator = 60
1.0
Accuracy Score for n_estimator = 70
0.9999791666666666
Accuracy Score for n_estimator = 80
0.9999791666666666
Accuracy Score for n_estimator = 90
0.9999791666666666
Accuracy Score for n_estimator = 100
0.9999791666666666


In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
#Tune n_estimators to 50 because there is no difference observed if we increase this.
rf=RandomForestClassifier(n_estimators=50, random_state = 4)
rf.fit(X_train,y_train)
pred=rf.predict(X_test)
print ("Classification Report")
print(classification_report(y_test, pred))
print ("Confusion Report")
print(confusion_matrix(y_test, pred))

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.96      0.96      1032
           3       0.96      0.96      0.96      1010
           4       0.96      0.97      0.97       982
           5       0.96      0.96      0.96       892
           6       0.97      0.97      0.97       958
           7       0.97      0.96      0.96      1028
           8       0.95      0.95      0.95       974
           9       0.96      0.94      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.96      0.96      0.96     10000
weighted avg       0.97      0.97      0.97     10000

Confusion Report
[[ 970    0    0    0    0    2    3    1    3    1]
 [   0 1125    2    2    0    2    2    0    1    1]
 [   8    0  994    4    4    1    4    8    9    0]
 [   2    0    9  968    0    9    0    9  

It seems that the model struggles to identify classes 8 or 9 the most because these have the lowest precision, recall, and f1 score.